development:
  adapter: mysql2
  database: did_store_dev
  pool: 5
  timeout: 5000

test: &test
  adapter: mysql2
  database: did_store_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: did_store
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
